name: "CI"
on:
  - push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19.2"
      - run: go install github.com/santhosh-tekuri/jsonschema/v5/cmd/jv@v5.0.1
      - run: jv -assertformat v1.json v1-sample.json
